import { Endpoint } from 'shared/http/domain/Endpoint'

export const fondosRotativos = {
  // Modulo Fondos Rotativos
  autorizadores_directos: new Endpoint('fondos-rotativos/autorizadores-directos'),
  empleados_saldos_fr: new Endpoint('fondos-rotativos/empleados-saldos-fr'),
  empleados_fondos_rotativos: new Endpoint('empleados-fondos-rotativos'),
  reporte_valores_fondos_empleados: new Endpoint('fondos-rotativos/reporte-valores-fondos'),
  tipo_fondo: new Endpoint('fondos-rotativos/tipo-fondo'),
  ajustes_saldos: new Endpoint('fondos-rotativos/ajustes-saldos'),
  gastos: new Endpoint('fondos-rotativos/gastos'),
  motivo_gasto: new Endpoint('fondos-rotativos/motivo-gasto'),
  gasto_coordinador: new Endpoint('fondos-rotativos/gasto-coordinador'),
  aprobar_gasto: new Endpoint('fondos-rotativos/aprobar-gasto'),
  rechazar_gasto: new Endpoint('fondos-rotativos/rechazar-gasto'),
  anular_gasto: new Endpoint('fondos-rotativos/anular-gasto'),
  aprobar_trnasferencia: new Endpoint('fondos-rotativos/aprobar-transferencia'),
  rechazar_transferencia: new Endpoint('fondos-rotativos/rechazar-transferencia'),
  anular_transferencia: new Endpoint('fondos-rotativos/anular-transferencia'),
  anular_acreditacion: new Endpoint('fondos-rotativos/anular-acreditacion'),
  detalle_fondo: new Endpoint('fondos-rotativos/detalles-viaticos'),
  sub_detalle_fondo: new Endpoint('fondos-rotativos/sub-detalles-viaticos'),
  saldo: new Endpoint('fondos-rotativos/saldo-grupo'),
  tipo_saldo: new Endpoint('fondos-rotativos/tipo-saldo'),
  fondo_rotativo_fecha_excel: new Endpoint('fondos-rotativos/reporte/fecha/excel'),
  fondo_rotativo_fecha_pdf: new Endpoint('fondos-rotativos/reporte/fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_pdf: new Endpoint('fondos-rotativos/autorizaciones_fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_excel: new Endpoint('fondos-rotativos/autorizaciones_fecha/excel'),
  consolidado_pdf: new Endpoint('fondos-rotativos/consolidado/pdf'),
  consolidado_excel: new Endpoint('fondos-rotativos/consolidado/excel'),
  consolidado_filtrado_pdf: new Endpoint('fondos-rotativos/consolidado_filtrado/pdf'),
  consolidado_filtrado_excel: new Endpoint('fondos-rotativos/consolidado_filtrado/excel'),
  autorizaciones_gastos: new Endpoint('fondos-rotativos/autorizaciones_gastos'),
  autorizaciones_transferencia: new Endpoint('fondos-rotativos/autorizaciones_transferencia'),
  umbral: new Endpoint('fondos-rotativos/umbral'),
  acreditacion: new Endpoint('fondos-rotativos/acreditacion'),
  transferencia: new Endpoint('fondos-rotativos/transferencia'),
  ultimo_saldo: new Endpoint('fondos-rotativos/ultimo_saldo'),
  monto_acreditar_usuario: new Endpoint('fondos-rotativos/monto_acreditar_usuario'),
  cortar_saldo: new Endpoint('fondos-rotativos/cortar_saldo'),

  reporte_saldo_actual_excel: new Endpoint('fondos-rotativos/reporte/saldo_actual/excel'),
  reporte_saldo_actual_pdf: new Endpoint('fondos-rotativos/reporte/saldo_actual/pdf'),
  reporte_solicitud_fondo_pdf: new Endpoint('fondos-rotativos/reporte/solicitud_fondo/pdf'),
  reporte_solicitud_fondo_excel: new Endpoint('fondos-rotativos/reporte/solicitud_fondo/excel'),
  gastocontabilidad: new Endpoint('fondos-rotativos/gastocontabilidad'),
  acreditacion_semana: new Endpoint('fondos-rotativos/acreditacion-semana'),
  valor_acreditar: new Endpoint('fondos-rotativos/valor-acreditar'),
  crear_cash_acreditacion_saldo: new Endpoint('fondos-rotativos/crear-cash-acreditacion-saldo/'),
  acreditacion_saldo_semana: new Endpoint('fondos-rotativos/acreditacion-saldo-semana/'),
  reporte_acreditacion_semanal: new Endpoint('fondos-rotativos/reporte-acreditacion-semanal/'),
  estados_viaticos: new Endpoint('fondos-rotativos/estados-viaticos'),

}
