import { Endpoint } from 'shared/http/domain/Endpoint'

export const medico = {
  gestion_cliente: new Endpoint('medico/tipos-elementos'),
  registros_empleados_examenes: new Endpoint(
    'medico/registros-empleados-examenes'
  ),
  categorias_examenes: new Endpoint('medico/categorias-examenes'),
  examenes: new Endpoint('medico/examenes'),
  estados_examenes: new Endpoint('medico/estados-examenes'),
  solicitudes_examenes: new Endpoint('medico/solicitudes-examenes'),
  tipos_examenes: new Endpoint('medico/tipos-examenes'),
  resultados_examenes: new Endpoint('medico/resultados-examenes'),
  archivo_cie: new Endpoint('medico/archivo-cie'),
  cie: new Endpoint('medico/cie'),
  configuraciones_examenes_categorias: new Endpoint('medico/configuraciones-examenes-categ'),
  configuraciones_examenes_campos: new Endpoint('medico/configuraciones-examenes-campos'),
  laboratorios_clinicos: new Endpoint('medico/laboratorios-clinicos'),
  respuestas_cuestionarios_empleados: new Endpoint('medico/resp-cuestionarios-empleados'),
  preguntas: new Endpoint('medico/preguntas'),
  citas_medicas: new Endpoint('medico/citas-medicas'),
  consultas_medicas: new Endpoint('medico/consultas-medicas'),
  diagnosticos_citas_medicas: new Endpoint('medico/diagnosticos-citas-medicas'),
  recetas: new Endpoint('medico/recetas'),
  esquemas_vacunas: new Endpoint('medico/esquemas-vacunas'),
  tipos_vacunas: new Endpoint('medico/tipos-vacunas'),
  reporte_cuestionario: new Endpoint('medico/reporte-cuestionario'),
  // configuracion_cuestionario_empleado: new Endpoint('medico/config-cuestionario-empleado'),
  configuracion_cuestionario_empleado: new Endpoint('medico/config-cuestionario-empleado'),
  fichas_aptitudes: new Endpoint('medico/fichas-aptitudes'),
  fichas_preocupacionales_consultar_informacion_defecto: new Endpoint('medico/ficha-preocupacional-informacion-defecto'),
  fichas_preocupacionales: new Endpoint('medico/fichas-preocupacionales'),
  fichas_periodicas: new Endpoint('medico/fichas-periodicas'),
  fichas_retiros: new Endpoint('medico/fichas-retiro'),
  religiones: new Endpoint('medico/religiones'),
  tipos_habitos_toxicos: new Endpoint('medico/tipos-habitos-toxicos'),
  sistemas_organos: new Endpoint('medico/sistemas-organos'),
  regiones_cuerpo: new Endpoint('medico/regiones-cuerpo'),
  categorias_examenes_fisicos: new Endpoint('medico/categorias-examenes-fisicos'),
  tipos_factores_riesgos: new Endpoint('medico/tipos-factores-riesgos'),
  categorias_factores_riesgos: new Endpoint('medico/categorias-factores-riesgos'),
  tipos_antecedentes_familiares: new Endpoint('medico/tipos-antecedentes-familiares'),
  identidades_generos: new Endpoint('medico/identidades-generos'),
  orientaciones_sexuales: new Endpoint('medico/orientaciones-sexuales'),
  tipos_antecedentes: new Endpoint('medico/tipos-antecedentes'),
  fichas_aptitudes_imprimir: new Endpoint('medico/fichas-aptitudes/imprimir'),
  fichas_preocupacionales_imprimir: new Endpoint('medico/fichas-preocupacionales/imprimir'),
  fichas_retiros_imprimir: new Endpoint('medico/fichas-retiros/imprimir'),
  tipos_aptitudes_medicas_laborales: new Endpoint('medico/tipos-aptitudes-medicas-laborales'),
  tipos_eval_medicas_retiro: new Endpoint('medico/tipos-eval-medicas-retiro'),
}
