import { Endpoint } from 'shared/http/domain/Endpoint'

export const tareas = {
  dashboard_tareas: new Endpoint('tareas/dashboard'),
  etapas: new Endpoint('tareas/etapas'),
  proyectos: new Endpoint('tareas/proyectos'),
  tareas: new Endpoint('tareas/tareas'),
  subtareas: new Endpoint('tareas/subtareas'),
  actualizar_fechas_reagendar: new Endpoint(
    'tareas/subtareas/actualizar-fechas-reagendar'
  ),
  actualizar_fechas_reagendar_tarea: new Endpoint(
    'tareas/tareas/actualizar-fechas-reagendar'
  ),
  centros_costos: new Endpoint('tareas/centros-costos'),
  subcentros_costos: new Endpoint('tareas/subcentros-costos'),
  trabajo_asignado: new Endpoint('tareas/trabajo-asignado'),
  pausas_subtareas: new Endpoint('tareas/subtareas/obtener-pausas'),
  suspendidos_subtareas: new Endpoint('tareas/subtareas/obtener-suspendidos'),
  tipos_trabajos: new Endpoint('tareas/tipos-trabajos'),
  causas_intervenciones: new Endpoint('tareas/causas-intervenciones'),
  rutas_tareas: new Endpoint('tareas/rutas-tareas'),
  motivos_pausas: new Endpoint('tareas/motivos-pausas'),
  motivos_pendientes: new Endpoint('tareas/motivos-pendientes'),
  motivos_suspendidos: new Endpoint('tareas/motivos-suspendidos'),
  control_asistencias: new Endpoint('tareas/control-asistencias'),
  control_cambios: new Endpoint('tareas/control-cambios'),
  tareas_empleado: new Endpoint('tareas/tareas-empleado'),
  tipos_elementos: new Endpoint('tareas/tipos-elementos'),
  clientes_finales: new Endpoint('tareas/clientes-finales'),
  tendidos: new Endpoint('tareas/tendidos'),
  designar_lider_grupo: new Endpoint('tareas/designar-lider-grupo'),
  designar_secretario_grupo: new Endpoint('tareas/designar-secretario-grupo'),
  archivos_subtareas: new Endpoint('tareas/archivos-subtareas'),
  archivos_seguimientos: new Endpoint('tareas/archivos-seguimientos'),
  actualizar_materiales_empleados: new Endpoint('actualizar-materiales-empleados'),
  actualizar_cantidad_material_empleado: new Endpoint('actualizar-cantidad-material-empleado'),
  materiales_empleado_tarea: new Endpoint('tareas/materiales-empleado-tarea'),
  materiales_empleado: new Endpoint('tareas/materiales-empleado'),
  materiales_empleado_consolidado: new Endpoint('tareas/materiales-empleado-consolidado'),
  registros_tendidos: new Endpoint('tareas/registros-tendidos'),
  reportes_modulo_tareas: new Endpoint('tareas/reportes'),
  resumen_tendidos: new Endpoint('tareas/resumen-tendidos'),
  seguimientos: new Endpoint('tareas/seguimientos'),
  movilizacion_subtarea: new Endpoint('tareas/movilizacion-subtarea'),
  movilizacion_subtarea_destino_actual: new Endpoint(
    'tareas/movilizacion-subtarea-destino-actual'
  ),
  clientes: new Endpoint('clientes'),
  grupos: new Endpoint('grupos'),
  exportExcelSeguimiento: new Endpoint('tareas/export-seguimiento'),
  verificar_todas_subtareas_finalizadas: new Endpoint('tareas/verificar-todas-subtareas-finalizadas'),
  verificar_material_tarea_devuelto: new Endpoint('tareas/verificar-material-tarea-devuelto'),
  transferir_mis_tareas_activas: new Endpoint('tareas/transferir-mis-tareas-activas'),
  obtener_suma_material_tarea_usado: new Endpoint('tareas/obtener-suma-material-tarea-usado'),
  obtener_historial_material_tarea_usado_por_fecha: new Endpoint('tareas/obtener-historial-material-tarea-usado-por-fecha'),
  obtener_historial_material_stock_usado_por_fecha: new Endpoint('tareas/obtener-historial-material-stock-usado-por-fecha'),
  obtener_resumen_material_subtarea_usado: new Endpoint('tareas/obtener-resumen-material-subtarea-usado'),
  obtener_resumen_material_stock_usado: new Endpoint('tareas/obtener-resumen-material-stock-usado'),
  actualizar_cantidad_utilizada_historial: new Endpoint('tareas/actualizar-cantidad-utilizada-historial'),
  actualizar_cantidad_utilizada_historial_stock: new Endpoint('tareas/actualizar-cantidad-utilizada-historial-stock'),
  actualizar_cantidad_utilizada_tarea: new Endpoint('tareas/actualizar-cantidad-utilizada-tarea'),
  actualizar_cantidad_utilizada_stock: new Endpoint('tareas/actualizar-cantidad-utilizada-stock'),
  actividades_realizadas_seguimientos_subtareas: new Endpoint('tareas/actividades-realizadas-seguimientos-subtareas'),
  fechas_historial_materiales_usados: new Endpoint('tareas/obtener-fechas-historial-materiales-usados'),
  fechas_historial_materiales_stock_usados: new Endpoint('tareas/obtener-fechas-historial-materiales-stock-usados'),
  obtener_clientes_materiales_empleado: new Endpoint('tareas/obtener-clientes-materiales-empleado'),
  obtener_clientes_materiales_tarea: new Endpoint('tareas/obtener-clientes-materiales-tarea'),
  transferencias_productos_empleados: new Endpoint('tareas/transferencias-productos-empleados'),
  reporte_materiales_utilizados: new Endpoint('tareas/reporte-materiales-utilizados'),
  reporte_materiales: new Endpoint('tareas/reporte-materiales'),
  alimentacion_grupos: new Endpoint('tareas/alimentacion-grupos'),
  nodos: new Endpoint('tareas/nodos'),
}
