import { ColumnConfig } from 'components/tables/domain/ColumnConfig'
import { estadosTrabajoArray } from 'config/utils'
import { Trabajo } from './Trabajo'

export const configuracionColumnasTrabajo: ColumnConfig<Trabajo>[] = [
  {
    name: 'codigo_tarea_cliente',
    field: 'codigo_tarea_cliente',
    label: 'Tarea Cliente',
    align: 'left',
    sortable: true,
  },
  {
    name: 'tarea',
    field: 'tarea',
    label: 'Tarea JP',
    align: 'left',
    sortable: true,
  },
  {
    name: 'codigo_trabajo',
    field: 'codigo_trabajo',
    label: 'Código de trabajo',
    align: 'left',
    sortable: true,
  },
  {
    name: 'coordinador',
    field: 'coordinador',
    label: 'Coordinador',
    align: 'left',
  },
  {
    name: 'estado',
    field: 'estado',
    label: 'Estado',
    align: 'left',
    type: 'select',
    options: estadosTrabajoArray
  },
  {
    name: 'titulo',
    field: 'titulo',
    label: 'Título del trabajo',
    align: 'left',
  },
  {
    name: 'tipo_trabajo',
    field: 'tipo_trabajo',
    label: 'Tipo de trabajo',
    align: 'left',
  },
  {
    name: 'fecha_solicitud',
    field: 'fecha_solicitud',
    label: 'Fecha solicitud',
    align: 'left',
    type: 'date',
  },
  {
    name: 'es_ventana',
    field: 'es_ventana',
    label: 'Es ventana',
    align: 'left',
    type: 'boolean',
  },
  {
    name: 'fecha_hora_creacion',
    field: 'fecha_hora_creacion',
    label: 'Fecha y hora de creación',
    align: 'left',
  },
  {
    name: 'fecha_agendado',
    field: 'fecha_agendado',
    label: 'Fecha de agendamiento',
    align: 'left',
    type: 'date',
  },
  {
    name: 'hora_inicio_agendado',
    field: 'hora_inicio_agendado',
    label: 'Hora inicio de agendamiento',
    align: 'left',
  },
  {
    name: 'hora_fin_agendado',
    field: 'hora_fin_agendado',
    label: 'Hora fin de agendamiento',
    align: 'left',
  },
  {
    name: 'fecha_hora_asignacion',
    field: 'fecha_hora_asignacion',
    label: 'Fecha y hora de asignación',
    align: 'left',
  },
  {
    name: 'fecha_hora_ejecucion',
    field: 'fecha_hora_ejecucion',
    label: 'Fecha y hora de ejecución',
    align: 'left',
  },
  {
    name: 'fecha_hora_realizado',
    field: 'fecha_hora_realizado',
    label: 'Fecha y hora de realizado',
    align: 'left',
  },
  {
    name: 'fecha_hora_finalizacion',
    field: 'fecha_hora_finalizacion',
    label: 'Fecha y hora de finalización',
    align: 'left',
  },
  {
    name: 'dias_ocupados',
    field: 'dias_ocupados',
    label: 'Días ocupados',
    align: 'left',
    type: 'number',
  },
  {
    name: 'fecha_hora_suspendido',
    field: 'fecha_hora_suspendido',
    label: 'Fecha y hora de suspención',
    align: 'left',
  },
  {
    name: 'causa_suspencion',
    field: 'causa_suspencion',
    label: 'Causa de suspención',
    align: 'left',
  },
  {
    name: 'fecha_hora_cancelacion',
    field: 'fecha_hora_cancelacion',
    label: 'Fecha y hora de cancelación',
    align: 'left',
  },
  {
    name: 'causa_cancelacion',
    field: 'causa_cancelacion',
    label: 'Causa de cancelación',
    align: 'left',
  },
  {
    name: 'empleados',
    field: 'empleados',
    label: 'Empleados responsables',
    align: 'left',
  },
  {
    name: 'grupos',
    field: 'grupos',
    label: 'Grupos responsables',
    align: 'left',
  },
  {
    name: 'trabajo_dependiente',
    field: 'trabajo_dependiente',
    label: 'Depende de',
    align: 'left',
  },
  {
    name: 'canton',
    field: 'canton',
    label: 'Cantón',
    align: 'left',
  },
  {
    name: 'cliente',
    field: 'cliente',
    label: 'Cliente',
    align: 'left',
    sortable: true,
  },
  {
    name: 'proyecto',
    field: 'proyecto',
    label: 'Proyecto',
    align: 'left',
    sortable: true,
  },
]
