import { Endpoint } from 'shared/http/domain/Endpoint'

export const apiConfig = {
  // URL_BASE: 'http://localhost:8000',
  URL_BASE: process.env.API_URL,
}

export const endpoints = {
  // Autenticacion
  csrf_cookie: new Endpoint('api/csrf-cookie', false),
  usuarios: new Endpoint('usuarios'),
  login: new Endpoint('usuarios/login'),
  logout: new Endpoint('usuarios/logout'),
  cambiarContrasena: new Endpoint('usuarios/cambiar-contrasena'),
  enviar_correo_recuperacion: new Endpoint('usuarios/recuperar-password'),
  recuperacion_cuenta: new Endpoint('usuarios/validar-token'),
  api_user: new Endpoint('user'),
  reset_password: new Endpoint('usuarios/reset-password'),
  perfil_usuario: new Endpoint('user/profile-information', false),
  cambiar_contrasena: new Endpoint('user/password', false),
  roles: new Endpoint('user/roles'),
  fecha: new Endpoint('obtener-fecha'),
  hora: new Endpoint('obtener-hora'),
  //configuraciones: new Endpoint('configuraciones'),
  tablero: new Endpoint('tablero'),
  // Permisos
  todos_permisos: new Endpoint('permisos'),
  permisos_roles_usuario: new Endpoint('permisos_roles_usuario'),
  permisos_administrar: new Endpoint('permisos_administrar'),
  asignar_permisos: new Endpoint('asignar-permisos'),
  asignar_permisos_individual: new Endpoint('asignar-permisos-usuario'),
  crear_permiso: new Endpoint('crear-permiso'),
  // Ubicacion
  paises: new Endpoint('paises'),
  provincias: new Endpoint('provincias'),
  cantones: new Endpoint('cantones'),
  parroquias: new Endpoint('parroquias'),

  // Modulo de RR HH
  cargos: new Endpoint('cargos'),
  motivo_permiso_empleado: new Endpoint('recursos-humanos/motivo_permiso_empleado'),
  estado_permiso_empleado: new Endpoint('recursos-humanos/estado_permiso_empleado'),
  tipo_contrato: new Endpoint('recursos-humanos/tipo_contrato'),
  permiso_empleado: new Endpoint('recursos-humanos/permiso_empleado'),
  licencia_empleado: new Endpoint('recursos-humanos/licencia_empleado'),
  prestamo_empresarial : new Endpoint('recursos-humanos/prestamo_empresarial'),
  solicitud_prestamo_empresarial : new Endpoint('recursos-humanos/solicitud_prestamo_empresarial'),
  anticipo : new Endpoint('recursos-humanos/anticipo'),
  rol_pago : new Endpoint('recursos-humanos/rol_pago'),
  datos_empleado : new Endpoint('recursos-humanos/datos_empleado/'),
  activos_fijos: new Endpoint('activos-fijos'),
  empleados: new Endpoint('empleados'),
  allroles: new Endpoint('roles'),
  concepto_ingreso: new Endpoint('recursos-humanos/concepto_ingreso'),
  descuentos_generales: new Endpoint('recursos-humanos/descuentos_generales'),
  descuentos_ley: new Endpoint('recursos-humanos/descuentos_ley'),
  multa: new Endpoint('recursos-humanos/multa'),
  prestamos_quirorafario_empleado: new Endpoint('recursos-humanos/prestamos_quirorafario_empleado'),
  prestamos_hipotecario_empleado: new Endpoint('recursos-humanos/prestamos_hipotecario_empleado'),
  extension_covertura_salud_empleado: new Endpoint('recursos-humanos/extension_covertura_salud_empleado'),
  horas_extras_tipo: new Endpoint('recursos-humanos/horas_extras_tipo'),
  horas_extras_subtipo: new Endpoint('recursos-humanos/horas_extras_subtipo'),
  forma_pago: new Endpoint('forma_pago'),
  sueldo_basico: new Endpoint('recursos-humanos/sueldo_basico'),
  nivel_endeudamiento: new Endpoint('recursos-humanos/nivel_endeudamiento'),
  aprobar_prestamo_empresarial: new Endpoint('recursos-humanos/aprobar_prestamo_empresarial'),
  rechazar_prestamo_empresarial: new Endpoint('recursos-humanos/rechazar_prestamo_empresarial'),
  vacacion: new Endpoint('recursos-humanos/vacacion'),
  archivo_permiso_empleado: new Endpoint('recursos-humanos/archivo_permiso_empleado'),
  archivo_licencia_empleado: new Endpoint('recursos-humanos/archivo_licencia_empleado'),




  //Modulo de Vehiculos
  combustibles: new Endpoint('vehiculos/combustibles'),
  vehiculos: new Endpoint('vehiculos/vehiculos'),
  bitacoras_vehiculos: new Endpoint('vehiculos/bitacoras-vehiculos'),
  empleados_choferes: new Endpoint('vehiculos/empleados-choferes'),

  // Modulo de Bodega
  autorizaciones: new Endpoint('autorizaciones'),
  categorias: new Endpoint('categorias'),
  condiciones: new Endpoint('condiciones'),
  comprobantes: new Endpoint('comprobantes'),
  estados_transacciones: new Endpoint('estados'),
  empleados_roles: new Endpoint('empleados-roles'), //con esta ruta se obtienen los empleados por el/los roles especificados
  control_stocks: new Endpoint('control-stocks'),
  codigos_clientes: new Endpoint('codigos-clientes'),
  detalles: new Endpoint('detalles'),
  devoluciones: new Endpoint('devoluciones'),
  detalle_producto_transaccion: new Endpoint('detalles-productos-transacciones'),
  discos: new Endpoint('discos'),
  comprobantes_filtrados: new Endpoint('comprobantes-filtrados'),
  egresos_filtrados: new Endpoint('egresos-filtrados'),
  empresas: new Endpoint('empresas'),
  rams: new Endpoint('rams'),
  inventarios: new Endpoint('inventarios'),
  hilos: new Endpoint('hilos'),
  marcas: new Endpoint('marcas'),
  modelos: new Endpoint('modelos'),
  movimientos: new Endpoint('movimientos-productos'),
  motivos: new Endpoint('motivos'),
  notificaciones: new Endpoint('notificaciones'),
  pedidos: new Endpoint('pedidos'),
  proveedores: new Endpoint('proveedores'),
  procesadores: new Endpoint('procesadores'),
  prestamos: new Endpoint('prestamos'),
  productos: new Endpoint('productos'),
  productos_perchas: new Endpoint('productos-perchas'),
  sucursales: new Endpoint('sucursales'),
  spans: new Endpoint('spans'),
  tipos_fibras: new Endpoint('tipos-fibras'),
  tipos_transacciones: new Endpoint('tipos-transacciones'),
  transacciones: new Endpoint('transacciones'),
  transacciones_egresos: new Endpoint('transacciones-egresos'),
  transacciones_ingresos: new Endpoint('transacciones-ingresos'),
  gestionar_egresos: new Endpoint('gestionar-egresos'),
  transferencias: new Endpoint('transferencias'),
  traspasos: new Endpoint('traspasos'),
  subtipos_transacciones: new Endpoint('subtipos-transacciones'),
  perchas: new Endpoint('perchas'),
  pisos: new Endpoint('pisos'),
  ubicaciones: new Endpoint('ubicaciones'),
  unidades_medidas: new Endpoint('unidades-medidas'),
  imagenes_adicionales: new Endpoint('imagenes-adicionales'),
  materiales_pedidos: new Endpoint('transacciones-egresos/materiales'),
  /* REPORTES BODEGA  */
  reporte_inventario: new Endpoint('reporte-inventario'),
  kardex: new Endpoint('kardex'),

  /********************
  * Modulo de tareas
  *********************/
  proyectos: new Endpoint('tareas/proyectos'),
  tareas: new Endpoint('tareas/tareas'),
  subtareas: new Endpoint('tareas/subtareas'),
  actualizar_fechas_reagendar: new Endpoint('tareas/subtareas/actualizar-fechas-reagendar'),
  actualizar_fechas_reagendar_tarea: new Endpoint('tareas/tareas/actualizar-fechas-reagendar'),
  trabajo_asignado: new Endpoint('tareas/trabajo-asignado'),
  pausas_subtareas: new Endpoint('tareas/subtareas/obtener-pausas'),
  suspendidos_subtareas: new Endpoint('tareas/subtareas/obtener-suspendidos'),
  tipos_trabajos: new Endpoint('tareas/tipos-trabajos'),
  causas_intervenciones: new Endpoint('tareas/causas-intervenciones'),
  rutas_tareas: new Endpoint('tareas/rutas-tareas'),
  motivos_pausas: new Endpoint('tareas/motivos-pausas'),
  motivos_pendientes: new Endpoint('tareas/motivos-pendientes'),
  motivos_suspendidos: new Endpoint('tareas/motivos-suspendidos'),
  control_asistencias: new Endpoint('tareas/control-asistencias'),
  control_cambios: new Endpoint('tareas/control-cambios'),
  tipos_elementos: new Endpoint('tareas/tipos-elementos'),
  clientes_finales: new Endpoint('tareas/clientes-finales'),
  tendidos: new Endpoint('tareas/tendidos'),
  designar_lider_grupo: new Endpoint('tareas/designar-lider-grupo'),
  designar_secretario_grupo: new Endpoint('tareas/designar-secretario-grupo'),
  archivos_subtareas: new Endpoint('tareas/archivos-subtareas'),
  archivos_seguimientos: new Endpoint('tareas/archivos-seguimientos'),
  materiales_empleado_tarea: new Endpoint('tareas/materiales-empleado-tarea'),
  materiales_empleado: new Endpoint('tareas/materiales-empleado'),
  registros_tendidos: new Endpoint('tareas/registros-tendidos'),
  reportes_modulo_tareas: new Endpoint('tareas/reportes'),
  resumen_tendidos: new Endpoint('tareas/resumen-tendidos'),
  seguimientos: new Endpoint('tareas/seguimientos'),
  movilizacion_subtarea: new Endpoint('tareas/movilizacion-subtarea'),
  movilizacion_subtarea_destino_actual: new Endpoint('tareas/movilizacion-subtarea-destino-actual'),
  clientes: new Endpoint('clientes'),
  grupos: new Endpoint('grupos'),
  exportExcelSeguimiento: new Endpoint('tareas/export-seguimiento'),
  verificar_todas_subtareas_finalizadas: new Endpoint('tareas/verificar-todas-subtareas-finalizadas'),
  verificar_material_tarea_devuelto: new Endpoint('tareas/verificar-material-tarea-devuelto'),
  transferir_mis_tareas_activas: new Endpoint('tareas/transferir-mis-tareas-activas'),

  // Modulo Fondos Rotativos
  tipo_fondo: new Endpoint('fondos-rotativos/tipo-fondo'),
  gastos: new Endpoint('fondos-rotativos/gastos'),
  motivo_gasto: new Endpoint('fondos-rotativos/motivo-gasto'),
  gasto_coordinador: new Endpoint('fondos-rotativos/gasto-coordinador'),
  aprobar_gasto: new Endpoint('fondos-rotativos/aprobar-gasto'),
  rechazar_gasto: new Endpoint('fondos-rotativos/rechazar-gasto'),
  anular_gasto: new Endpoint('fondos-rotativos/anular-gasto'),
  aprobar_trnasferencia: new Endpoint('fondos-rotativos/aprobar-transferencia'),
  rechazar_transferencia: new Endpoint('fondos-rotativos/rechazar-transferencia'),
  anular_transferencia: new Endpoint('fondos-rotativos/anular-transferencia'),
  anular_acreditacion: new Endpoint('fondos-rotativos/anular-acreditacion'),
  detalle_fondo: new Endpoint('fondos-rotativos/detalles-viaticos'),
  sub_detalle_fondo: new Endpoint('fondos-rotativos/sub-detalles-viaticos'),
  saldo: new Endpoint('fondos-rotativos/saldo-grupo'),
  tipo_saldo: new Endpoint('fondos-rotativos/tipo-saldo'),
  usuarios_autorizadores: new Endpoint('usuarios-autorizadores'),
  lista_usuarios: new Endpoint('lista-usuarios'),
  fondo_rotativo_fecha_excel: new Endpoint('fondos-rotativos/reporte/fecha/excel'),
  fondo_rotativo_fecha_pdf: new Endpoint('fondos-rotativos/reporte/fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_pdf: new Endpoint('fondos-rotativos/autorizaciones_fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_excel: new Endpoint('fondos-rotativos/autorizaciones_fecha/excel'),
  consolidado_pdf: new Endpoint('fondos-rotativos/consolidado/pdf'),
  consolidado_excel: new Endpoint('fondos-rotativos/consolidado/excel'),
  consolidado_filtrado_pdf: new Endpoint('fondos-rotativos/consolidado_filtrado/pdf'),
  consolidado_filtrado_excel: new Endpoint('fondos-rotativos/consolidado_filtrado/excel'),
  autorizaciones_gastos: new Endpoint('fondos-rotativos/autorizaciones_gastos'),
  autorizaciones_transferencia: new Endpoint('fondos-rotativos/autorizaciones_transferencia'),

  acreditacion: new Endpoint('fondos-rotativos/acreditacion'),
  transferencia: new Endpoint('fondos-rotativos/transferencia'),
  ultimo_saldo: new Endpoint('fondos-rotativos/ultimo_saldo/'),
  reporte_saldo_actual_excel: new Endpoint('fondos-rotativos/reporte/saldo_actual/excel'),
  reporte_saldo_actual_pdf: new Endpoint('fondos-rotativos/reporte/saldo_actual/pdf'),
  reporte_solicitud_fondo_pdf: new Endpoint('fondos-rotativos/reporte/solicitud_fondo/pdf'),
  reporte_solicitud_fondo_excel: new Endpoint('fondos-rotativos/reporte/solicitud_fondo/excel'),
  gastocontabilidad: new Endpoint('fondos-rotativos/gastocontabilidad'),

  /********************
  * Modulo de tickets
  *********************/
  departamentos: new Endpoint('recursos-humanos/departamentos'),
  tickets: new Endpoint('tickets/tickets'),
  tipos_tickets: new Endpoint('tickets/tipos-tickets'),
  categorias_tipos_tickets: new Endpoint('tickets/categorias-tipos-tickets'),
  archivos_tickets: new Endpoint('tickets/archivos-tickets'),
  archivos_seguimientos_tickets: new Endpoint('tickets/archivos-seguimientos-tickets'),
  motivos_pausas_tickets: new Endpoint('tickets/motivos-pausas-tickets'),
  motivos_cancelados_tickets: new Endpoint('tickets/motivos-cancelados-tickets'),
  cambiar_responsable_ticket: new Endpoint('tickets/tickets/cambiar-responsable'),
  actividades_realizadas_seguimientos_tickets: new Endpoint('tickets/actividades-realizadas-seguimientos-tickets'),
  pausas_tickets: new Endpoint('tickets/tickets/obtener-pausas'),
  rechazos_tickets: new Endpoint('tickets/tickets/obtener-rechazados'),
}
