import { Endpoint } from 'shared/http/domain/Endpoint'

export const apiConfig = {
  URL_BALSE: 'http://localhost:8000',
}

export const endpoints = {
  // Autenticacion
  csrf_cookie: new Endpoint('sanctum/csrf-cookie', false),
  login: new Endpoint('usuarios/login'),
  logout: new Endpoint('usuarios/logout'),
  api_user: new Endpoint('user'),
  reset_password: new Endpoint('reset-password', false),
  perfil_usuario: new Endpoint('user/profile-information', false),
  cambiar_contrasena: new Endpoint('user/password', false),
  roles: new Endpoint('user/roles'),
  permisos: new Endpoint('user/permisos'),
  fecha: new Endpoint('obtener-fecha'),
  hora: new Endpoint('obtener-hora'),
  //configuraciones: new Endpoint('configuraciones/'),
  tablero: new Endpoint('tablero/'),
  // Ubicacion
  paises: new Endpoint('paises/'),
  provincias: new Endpoint('provincias/'),
  cantones: new Endpoint('cantones/'),

  // Modulo de RR HH
  activos_fijos: new Endpoint('activos-fijos/'),
  empleados: new Endpoint('empleados/'),
  allroles: new Endpoint('roles/'),

  // Modulo de Bodega
  autorizaciones: new Endpoint('autorizaciones/'),
  categorias: new Endpoint('categorias/'),
  condiciones: new Endpoint('condiciones/'),
  estados_transacciones: new Endpoint('estados/'),
  control_stocks: new Endpoint('control-stocks/'),
  codigos_clientes: new Endpoint('codigos-clientes/'),
  detalles: new Endpoint('detalles/'),
  devoluciones: new Endpoint('devoluciones/'),
  detalle_producto_transaccion: new Endpoint('detalles-productos-transacciones/'),
  discos: new Endpoint('discos/'),
  rams: new Endpoint('rams/'),
  inventarios: new Endpoint('inventarios/'),
  hilos: new Endpoint('hilos/'),
  marcas: new Endpoint('marcas/'),
  modelos: new Endpoint('modelos/'),
  movimientos: new Endpoint('movimientos-productos/'),
  motivos: new Endpoint('motivos/'),
  pedidos: new Endpoint('pedidos/'),
  procesadores: new Endpoint('procesadores/'),
  prestamos: new Endpoint('prestamos/'),
  productos: new Endpoint('productos/'),
  productos_perchas: new Endpoint('productos-perchas/'),
  sucursales: new Endpoint('sucursales/'),
  spans: new Endpoint('spans/'),
  tipos_fibras: new Endpoint('tipos-fibras/'),
  tipos_transacciones: new Endpoint('tipos-transacciones/'),
  transacciones: new Endpoint('transacciones/'),
  transacciones_egresos: new Endpoint('transacciones-egresos/'),
  transacciones_ingresos: new Endpoint('transacciones-ingresos/'),
  transferencias: new Endpoint('transferencias/'),
  traspasos: new Endpoint('traspasos/'),
  subtipos_transacciones: new Endpoint('subtipos-transacciones/'),
  perchas: new Endpoint('perchas/'),
  pisos: new Endpoint('pisos/'),
  ubicaciones: new Endpoint('ubicaciones/'),
  imagenes_adicionales: new Endpoint('imagenes-adicionales/'),
  materiales_pedidos: new Endpoint('transacciones-egresos/materiales/'),

  // Modulo de tareas
  proyectos: new Endpoint('proyectos/'),
  tareas: new Endpoint('tareas/'),
  subtareas: new Endpoint('subtareas/'),
  subtareas_asignadas: new Endpoint('subtareas-asignadas/'),
  pausas_subtareas: new Endpoint('subtareas/pausas'),
  tipos_trabajos: new Endpoint('tipos-trabajos/'),
  control_asistencias: new Endpoint('control-asistencias/'),
  control_cambios: new Endpoint('control-cambios/'),
  tipos_elementos: new Endpoint('tipos-elementos/'),
  clientes: new Endpoint('clientes/'),
  grupos: new Endpoint('grupos/'),
  clientes_finales: new Endpoint('clientes-finales/'),
  tendidos: new Endpoint('tendidos/'),
  intercambiar_jefe_cuadrilla: new Endpoint('intercambiar-jefe-cuadrilla/'),
  intercambiar_secretario_cuadrilla: new Endpoint('intercambiar-secretario-cuadrilla/'),
  archivos_subtareas: new Endpoint('archivos-subtareas/'),
  materiales_despachados: new Endpoint('transacciones-egresos/materiales-despachados/'),
  materiales_despachados_sin_bobina: new Endpoint('materiales-grupo-tarea/'),
  // materiales_despachados_con_bobina: new Endpoint('transacciones-egresos/materiales-despachados-con-bobina/'),
  bobinas_grupo_tarea: new Endpoint('bobinas-grupo-tarea/'),
  registros_tendidos: new Endpoint('registros-tendidos/'),
  reportes_control_materiales: new Endpoint('reportes-control-materiales'),
  resumen_tendidos: new Endpoint('resumen-tendidos'),
}
