import { Endpoint } from 'shared/http/domain/Endpoint'

export const apiConfig = {
  // URL_BASE: 'http://localhost:8000',
  URL_BASE: process.env.API_URL,
}

export const endpoints = {
  // Autenticacion
  csrf_cookie: new Endpoint('api/csrf-cookie', false),
  usuarios: new Endpoint('usuarios'),
  login: new Endpoint('usuarios/login'),
  logout: new Endpoint('usuarios/logout'),
  cambiarContrasena: new Endpoint('usuarios/cambiar-contrasena'),
  enviar_correo_recuperacion: new Endpoint('usuarios/recuperar-password'),
  recuperacion_cuenta: new Endpoint('usuarios/validar-token'),
  api_user: new Endpoint('user'),
  reset_password: new Endpoint('usuarios/reset-password'),
  perfil_usuario: new Endpoint('user/profile-information', false),
  cambiar_contrasena: new Endpoint('user/password', false),
  roles: new Endpoint('user/roles'),
  permisos: new Endpoint('user/permisos'),
  fecha: new Endpoint('obtener-fecha'),
  hora: new Endpoint('obtener-hora'),
  //configuraciones: new Endpoint('configuraciones'),
  tablero: new Endpoint('tablero'),
  // Ubicacion
  paises: new Endpoint('paises'),
  provincias: new Endpoint('provincias'),
  cantones: new Endpoint('cantones'),
  parroquias: new Endpoint('parroquias'),

  // Modulo de RR HH
  cargos: new Endpoint('cargos'),
  activos_fijos: new Endpoint('activos-fijos'),
  empleados: new Endpoint('empleados'),
  allroles: new Endpoint('roles'),

  // Modulo de Bodega
  autorizaciones: new Endpoint('autorizaciones'),
  categorias: new Endpoint('categorias'),
  condiciones: new Endpoint('condiciones'),
  estados_transacciones: new Endpoint('estados'),
  control_stocks: new Endpoint('control-stocks'),
  codigos_clientes: new Endpoint('codigos-clientes'),
  detalles: new Endpoint('detalles'),
  devoluciones: new Endpoint('devoluciones'),
  detalle_producto_transaccion: new Endpoint('detalles-productos-transacciones'),
  discos: new Endpoint('discos'),
  empresas: new Endpoint('empresas'),
  rams: new Endpoint('rams'),
  inventarios: new Endpoint('inventarios'),
  hilos: new Endpoint('hilos'),
  marcas: new Endpoint('marcas'),
  modelos: new Endpoint('modelos'),
  movimientos: new Endpoint('movimientos-productos'),
  motivos: new Endpoint('motivos'),
  notificaciones: new Endpoint('notificaciones'),
  pedidos: new Endpoint('pedidos'),
  proveedores: new Endpoint('proveedores'),
  procesadores: new Endpoint('procesadores'),
  prestamos: new Endpoint('prestamos'),
  productos: new Endpoint('productos'),
  productos_perchas: new Endpoint('productos-perchas'),
  sucursales: new Endpoint('sucursales'),
  spans: new Endpoint('spans'),
  tipos_fibras: new Endpoint('tipos-fibras'),
  tipos_transacciones: new Endpoint('tipos-transacciones'),
  transacciones: new Endpoint('transacciones'),
  transacciones_egresos: new Endpoint('transacciones-egresos'),
  transacciones_ingresos: new Endpoint('transacciones-ingresos'),
  transferencias: new Endpoint('transferencias'),
  traspasos: new Endpoint('traspasos'),
  subtipos_transacciones: new Endpoint('subtipos-transacciones'),
  perchas: new Endpoint('perchas'),
  pisos: new Endpoint('pisos'),
  ubicaciones: new Endpoint('ubicaciones'),
  unidades_medidas: new Endpoint('unidades-medidas'),
  imagenes_adicionales: new Endpoint('imagenes-adicionales'),
  materiales_pedidos: new Endpoint('transacciones-egresos/materiales'),

  // Modulo de tareas
  proyectos: new Endpoint('proyectos'),
  tareas: new Endpoint('tareas'),
  subtareas: new Endpoint('subtareas'),
  actualizar_fechas_reagendar: new Endpoint('subtareas/actualizar-fechas-reagendar'),
  trabajos: new Endpoint('trabajos'),
  trabajo_asignado: new Endpoint('trabajo-asignado'),
  pausas_subtareas: new Endpoint('subtareas/pausas'),
  tipos_trabajos: new Endpoint('tipos-trabajos'),
  control_asistencias: new Endpoint('control-asistencias'),
  control_cambios: new Endpoint('control-cambios'),
  tipos_elementos: new Endpoint('tipos-elementos'),
  clientes: new Endpoint('clientes'),
  grupos: new Endpoint('grupos'),
  clientes_finales: new Endpoint('clientes-finales'),
  tendidos: new Endpoint('tendidos'),
  designar_lider_grupo: new Endpoint('designar-lider-grupo'),
  designar_secretario_grupo: new Endpoint('designar-secretario-grupo'),
  archivos_subtareas: new Endpoint('archivos-subtareas'),
  materiales_despachados: new Endpoint('transacciones-egresos/materiales-despachados'),
  materiales_despachados_sin_bobina: new Endpoint('materiales-empleado-tarea'),
  // materiales_despachados_con_bobina: new Endpoint('transacciones-egresos/materiales-despachados-con-bobina'),
  bobinas_empleado_tarea: new Endpoint('bobinas-empleado-tarea'),
  registros_tendidos: new Endpoint('registros-tendidos'),
  reportes_control_materiales: new Endpoint('reportes-control-materiales'),
  resumen_tendidos: new Endpoint('resumen-tendidos'),

  // Modulo Fondos Rotativos
  tipo_fondo: new Endpoint('fondos-rotativos/tipo-fondo'),
  gastos: new Endpoint('fondos-rotativos/gastos'),
  detalle_fondo: new Endpoint('fondos-rotativos/detalles-viaticos'),
  sub_detalle_fondo: new Endpoint('fondos-rotativos/sub-detalles-viaticos'),
  saldo: new Endpoint('fondos-rotativos/saldo-grupo'),
  tipo_saldo: new Endpoint('fondos-rotativos/tipo-saldo'),
  usuarios_autorizadores: new Endpoint('usuarios-autorizadores'),
  lista_usuarios: new Endpoint('lista-usuarios'),
  fondo_rotativo_fecha_excel: new Endpoint('fondos-rotativos/reporte/fecha/excel'),
  fondo_rotativo_fecha_pdf: new Endpoint('fondos-rotativos/reporte/fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_pdf: new Endpoint('fondos-rotativos/autorizaciones_fecha/pdf'),
  fondo_rotativo_autorizaciones_fecha_excel: new Endpoint('fondos-rotativos/autorizaciones_fecha/excel'),
  consolidado_pdf: new Endpoint('fondos-rotativos/consolidado/pdf'),
  consolidado_excel: new Endpoint('fondos-rotativos/consolidado/excel'),
  consolidado_filtrado_pdf: new Endpoint('fondos-rotativos/consolidado_filtrado/pdf'),
  consolidado_filtrado_excel: new Endpoint('fondos-rotativos/consolidado_filtrado/excel'),


  acreditacion: new Endpoint('fondos-rotativos/acreditacion'),
  ultimo_saldo: new Endpoint('fondos-rotativos/ultimo_saldo/'),
  reporte_saldo_actual_excel: new Endpoint('fondos-rotativos/reporte/saldo_actual/excel'),
  reporte_saldo_actual_pdf: new Endpoint('fondos-rotativos/reporte/saldo_actual/pdf'),
  gastocontabilidad: new Endpoint('fondos-rotativos/gastocontabilidad'),
  emergencias: new Endpoint('emergencias'),
}
