import { ColumnConfig } from 'components/tables/domain/ColumnConfig'
import { Subtarea } from 'gestionTrabajos/subtareas/domain/Subtarea'

export const configuracionColumnasTrabajoAsignado: ColumnConfig<Subtarea>[] = [
  {
    name: 'tarea',
    field: 'tarea',
    label: 'Cód. Tarea',
    align: 'left',
    sortable: true,
  },
  {
    name: 'codigo_subtarea',
    field: 'codigo_subtarea',
    label: 'Cód. Subtarea',
    align: 'left',
    sortable: true,
  },
  {
    name: 'titulo',
    field: 'titulo',
    label: 'Título',
    align: 'left',
    sortable: true,
  },
  {
    name: 'tipo_trabajo',
    field: 'tipo_trabajo',
    label: 'Tipo de trabajo',
    align: 'left',
  },
  {
    name: 'estado',
    field: 'estado',
    label: 'Estado',
    align: 'left',
    sortable: true,
  },
  {
    name: 'empleado',
    field: 'empleado',
    label: 'Empleado designado',
    align: 'left',
  },
  {
    name: 'grupo',
    field: 'grupo',
    label: 'Grupo designado',
    align: 'left',
  },
  {
    name: 'coordinador',
    field: 'coordinador',
    label: 'Coordinador',
    align: 'left',
  },
  {
    name: 'fecha_hora_agendado',
    field: 'fecha_hora_agendado',
    label: 'Fecha hora agendado',
    align: 'left',
    sortable: true,
  },
  {
    name: 'es_ventana',
    field: 'es_ventana',
    label: 'Es ventana',
    align: 'left',
  },
  {
    name: 'fecha_inicio_trabajo',
    field: 'fecha_inicio_trabajo',
    label: 'Fecha inicio de trabajo',
    align: 'left',
  },
  {
    name: 'hora_inicio_trabajo',
    field: 'hora_inicio_trabajo',
    label: 'Hora inicio de trabajo',
    align: 'left',
  },
  {
    name: 'hora_fin_trabajo',
    field: 'hora_fin_trabajo',
    label: 'Hora fin de trabajo',
    align: 'left',
  },
  {
    name: 'subtarea_dependiente',
    field: 'subtarea_dependiente',
    label: 'Depende de',
    align: 'left',
  },
  {
    name: 'proyecto',
    field: 'proyecto',
    label: 'Proyecto',
    align: 'left',
    sortable: true,
  },
  {
    name: 'etapa',
    field: 'etapa',
    label: 'Etapa',
    align: 'left',
    sortable: true,
  },
  {
    name: 'cliente_final',
    field: 'cliente_final',
    label: 'Cliente final',
    align: 'left',
    sortable: true,
  },
]
